// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: proto/ServiceOne.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceOneClient is the client API for ServiceOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceOneClient interface {
	HelloOne(ctx context.Context, in *HelloOneRequest, opts ...grpc.CallOption) (*HelloOneResponse, error)
}

type serviceOneClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOneClient(cc grpc.ClientConnInterface) ServiceOneClient {
	return &serviceOneClient{cc}
}

func (c *serviceOneClient) HelloOne(ctx context.Context, in *HelloOneRequest, opts ...grpc.CallOption) (*HelloOneResponse, error) {
	out := new(HelloOneResponse)
	err := c.cc.Invoke(ctx, "/ServiceOne/HelloOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOneServer is the server API for ServiceOne service.
// All implementations must embed UnimplementedServiceOneServer
// for forward compatibility
type ServiceOneServer interface {
	HelloOne(context.Context, *HelloOneRequest) (*HelloOneResponse, error)
	mustEmbedUnimplementedServiceOneServer()
}

// UnimplementedServiceOneServer must be embedded to have forward compatible implementations.
type UnimplementedServiceOneServer struct {
}

func (UnimplementedServiceOneServer) HelloOne(context.Context, *HelloOneRequest) (*HelloOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloOne not implemented")
}
func (UnimplementedServiceOneServer) mustEmbedUnimplementedServiceOneServer() {}

// UnsafeServiceOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceOneServer will
// result in compilation errors.
type UnsafeServiceOneServer interface {
	mustEmbedUnimplementedServiceOneServer()
}

func RegisterServiceOneServer(s grpc.ServiceRegistrar, srv ServiceOneServer) {
	s.RegisterService(&ServiceOne_ServiceDesc, srv)
}

func _ServiceOne_HelloOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOneServer).HelloOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServiceOne/HelloOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOneServer).HelloOne(ctx, req.(*HelloOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceOne_ServiceDesc is the grpc.ServiceDesc for ServiceOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServiceOne",
	HandlerType: (*ServiceOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloOne",
			Handler:    _ServiceOne_HelloOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ServiceOne.proto",
}
